Jumpstart.config = Jumpstart::Configuration.new({"application_name" => "Hefty-dev.com",
 "business_name" => "HeftyDev, LLC",
 "business_address" => "842 e grenoble dr",
 "domain" => "hefty-dev.com",
 "support_email" => "trevorjohnnels@gmail.com",
 "default_from_email" => "Hefty Dev <trevorjohnnels@gmail.com>",
 "background_job_processor" => "sidekiq",
 "email_provider" => "mailjet",
 "account_types" => "both",
 "apns" => false,
 "fcm" => false,
 "integrations" => [],
 "omniauth_providers" => [],
 "payment_processors" => [],
 "multitenancy" => [],
 "gems" => []})
